config/routes.rb
Rails.application.routes.draw do
  # Deviseのルート設定
  devise_for :users, controllers: {
    # コントローラーやオプションがある場合、ここに追記
    registrations: 'users/registrations' 
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'application#guest_sign_in'
  end

  # Root URL設定
  root to: 'pages#home'

  # それぞれのリソースに関する標準のCRUDルート
  resources :meals do
    collection do
      get 'calorie_search'
    end
  end
  resources :exercises
  resources :badges, only: [:index, :show]
  resources :goals
  resources :posts
  resources :user_badges, only: [:create, :destroy]

  # ダッシュボード
  resource :dashboard, only: [:show]
  resource :profile, only: [:show, :edit, :update]
  get 'profile/:id', to: 'profiles#show', as: 'profile_show'

  get 'privacy', to: 'pages#privacy', as: 'privacy'
  get 'service', to: 'pages#service', as: 'service'

  resources :exercises do
    collection do
      get 'calculate_calories'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  belongs_to :exercise_type

  validate :user_name_present

  private

  def user_name_present
    if user && user.name.blank?
      errors.add(:user, "name can't be blank")
    end
  end
end

app/models/exercise_type.rb
class ExerciseType < ApplicationRecord
  has_many :exercises
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/meal.rb
class Meal < ApplicationRecord
  enum meal_period: { breakfast: 0, lunch: 1, dinner: 2, nosh: 3 }
  enum meal_type: { self_catering: 0, eating_out: 1, to_go: 2, convenience_store: 3 }

  belongs_to :user
  has_many :meal_details, dependent: :destroy

  mount_uploader :meal_image, MealImageUploader

  validate :user_name_present

  private

  def user_name_present
    if user && user.name.blank?
      errors.add(:user, "name can't be blank")
    end
  end

end

app/models/meal_detail.rb
class MealDetail < ApplicationRecord
  belongs_to :meal
  validates :meal_title, presence: true
  validates :meal_weight, presence: true
  validates :meal_calorie, presence: true
  self.implicit_order_column = 'created_at'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  validate :user_name_present

  private

  def user_name_present
    if user && user.name.blank?
      errors.add(:user, "name can't be blank")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_default_public_settings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :goals
  accepts_nested_attributes_for :goals, reject_if: :all_blank, allow_destroy: true
  has_many :meals
  has_many :exercises
  has_many :posts
  has_many :user_badges
  has_many :badges, through: :user_badges

  mount_uploader :avatar, AvatarUploader

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # 他の必要な初期設定を追加
    end
  end

  private
  
  def set_default_public_settings
    self.age_public ||= false
    self.height_public ||= false
    self.weight_public ||= false
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  def index
    @goals = Goal.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @goal = Goal.new
  end

  def edit
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user

    if @goal.save
      redirect_to @goal, notice: 'Goal was successfully created.'
    else
      render :new
    end
  end

  def update
    if @goal.update(goal_params)
      redirect_to @goal, notice: 'Goal was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @goal.destroy
    redirect_to goals_url, notice: 'Goal was successfully destroyed.'
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :description, :start_date, :end_date, :target_weight)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def basal_metabolic_rate(user)
    return 0 unless user.current_weight && user.height && user.age
    if user.gender == "Male"
      return ((13.397 * user.current_weight) + (4.799 * user.height) - (5.677 * user.age) + 88.362 ) * 1.5
    elsif user.gender == "Female"
      return ((9.247 * user.current_weight) + (3.098 * user.height) - (4.33 * user.age) + 447.593 ) * 1.5
    else
      return 0
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake" class="font-top text-maincolor">
  <head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-96LYQWH39N"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-96LYQWH39N');
  </script>
    <title>DebuPrison</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= display_meta_tags(default_meta_tags) %>
    <link rel="icon" type="image/png" href="/favicon.png">

    <link href="https://fonts.googleapis.com/css2?family=Emblema+One&family=Kosugi+Maru&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/95ae21fd7d.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.12.3/dist/cdn.js" defer></script>

    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-JLLP5YDYPQ');
    </script>
  </head>

  <body>
    <% if user_signed_in? %>
<%= render 'shared/header' %>
<% else %>
<%= render 'shared/before_login_header' %>
<% end %>

<%= render 'shared/flash_message' %>

<%= yield %>

<%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header data-theme="retro" class="py-6 bg-blue-600 shadow-md">
  <div class="container mx-auto flex flex-wrap flex-col md:flex-row items-center px-4">
    
    <!-- Logo -->
    <div class="mb-4 md:mb-0">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', width: 220, height: 220, alt: "Diet Challenge Logo", class: "mx-auto md:mx-0" %>
      <% end %>
    </div>
    
    <!-- Navigation Links -->
    <div class="md:ml-auto flex flex-wrap items-center text-base md:text-xl justify-center mt-4 md:mt-0">
      <%= link_to (t 'defaults.loginpage'), new_user_session_path, class: "btn text-white bg-blue-800 hover:bg-blue-900 py-2 px-4 rounded mr-4" %>
      <%= link_to (t 'defaults.register_page'), new_user_registration_path, class: "btn text-white bg-green-500 hover:bg-green-600 py-2 px-4 rounded" %>
    </div>

  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object && object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> text-headfoot"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer data-theme="retro", class="p-10 text-xl bg-blue-500">
  <div class="flex-wrap justify-center text-headfoot">
    <p>Developed by yamashita</p>
    <%= link_to (t 'policy.privacy_policy'), privacy_path, class: "btn mr-5 text-headfoot"%>
    <%= link_to (t 'policy.terms_of_service'), service_path, class: "btn mr-5 text-headfoot"%>
  </div>
</footer>

app/views/shared/_header.html.erb
<style>
    .custom-green {
        background-color: #191970;
    }

    .dropdown-hover:hover .dropdown-content {
        display: block !important;
    }

    /* 追加: 親要素を動かさないためのスタイル */
    .dropdown-hover {
        position: relative;
    }

    .dropdown-content {
        position: absolute;
        top: 100%; /* ボタンの下に配置 */
        left: 0;
    }
    .menu-button-space {
        margin-right: 20px; /* あるいは、任意のピクセル数に変更して調整してください */
    }


    .dropdown-button {
        cursor: pointer; /* カーソルをポインタに変更 */
        position: relative;
        padding-right: 25px; /* アイコンスペースのためのパディング */
    }
    
    .dropdown-button::after {
        content: '▼'; /* ドロップダウンインジケータ */
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
        font-size: 12px;
    }
</style>

<header data-theme="retro" class="py-10 bg-blue-500">
  <div class="container mx-auto flex flex-wrap flex-col md:flex-row items-center">
    <div class="font-title">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', width: 220, height: 220, alt: "Diet Challenge Logo"%>
      <% end %>
    </div>
    <div class="md:ml-auto flex flex-wrap items-center text-base md:text-xl justify-center menu-button-space"> 
      <%= link_to (t 'dashboards.show.title'), dashboard_path, class: "text-headfoot custom-green shadow-md p-2 rounded text-white menu-button-space" %>

      <div class="relative inline-block dropdown-hover menu-button-space">
    <button class="btn btn-primary custom-green text-white my-1 dropdown-button shadow-md p-2 rounded">
      食事記録
    </button>
        <ul class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 absolute left-0" style="display: none;">
          <%= link_to '一覧', meals_path, class: "btn btn-primary custom-green text-white my-2 block shadow-md p-2 rounded" %>
          <%= link_to '作成', new_meal_path, class: "btn btn-primary custom-green text-white my-2 block shadow-md p-2 rounded" %>
        </ul>
      </div>

      <div class="relative inline-block dropdown-hover menu-button-space">
    <button class="btn btn-primary custom-green text-white my-1 dropdown-button shadow-md p-2 rounded">
          運動記録
        </button>
        <ul class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 absolute left-0" style="display: none;">
          <%= link_to '一覧', exercises_path, class: "btn btn-primary custom-green text-white my-2 block shadow-md p-2 rounded" %>
          <%= link_to '作成', new_exercise_path, class: "btn btn-primary custom-green text-white my-2 block shadow-md p-2 rounded" %>
        </ul>
      </div>

      <div class="relative inline-block dropdown-hover menu-button-space">
    <button class="btn btn-primary custom-green text-white my-1 dropdown-button shadow-md p-2 rounded">
          掲示板
        </button>
        <ul class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 absolute left-0" style="display: none;">
          <%= link_to '一覧', posts_path, class: "btn btn-primary custom-green text-white my-2 block shadow-md p-2 rounded" %>
          <%= link_to '作成', new_post_path, class: "btn btn-primary custom-green text-white my-2 block shadow-md p-2 rounded" %>
        </ul>
      </div>

      <div class="relative inline-block dropdown-hover menu-button-space">
    <button class="btn btn-primary custom-green text-white my-1 dropdown-button shadow-md p-2 rounded">
          プロフィール
        </button>
        <ul class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 absolute left-0" style="display: none;">
          <%= link_to '表示', profile_show_path(current_user.id), class: "btn btn-primary custom-green text-white my-2 block shadow-md p-2 rounded" %>
          <%= link_to '編集', edit_profile_path, class: "btn btn-primary custom-green text-white my-2 block shadow-md p-2 rounded" %>
        </ul>
      </div>

      <%= button_to (t 'defaults.logout'), destroy_user_session_path, method: :delete, class: "text-headfoot custom-green shadow-md p-2 rounded text-white" %>
      <div class="avatar">
        <div class="w-16 rounded-full">
          <%= image_tag current_user.avatar.present? ? current_user.avatar.url : 'default-avatar.png' %>
        </div>
      </div>
    </div>
  </div>
</header>