config/routes.rb
Rails.application.routes.draw do
  # Deviseのルート設定
  devise_for :users, controllers: {
    # コントローラーやオプションがある場合、ここに追記
    registrations: 'users/registrations' 
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'application#guest_sign_in'
  end

  # Root URL設定
  root to: 'pages#home'

  # それぞれのリソースに関する標準のCRUDルート
  resources :meals do
    collection do
      get 'calorie_search'
    end
  end
  resources :exercises
  resources :badges, only: [:index, :show]
  resources :goals
  resources :posts
  resources :user_badges, only: [:create, :destroy]

  # ダッシュボード
  resource :dashboard, only: [:show]
  resource :profile, only: [:show, :edit, :update]
  get 'profile/:id', to: 'profiles#show', as: 'profile_show'

  get 'privacy', to: 'pages#privacy', as: 'privacy'
  get 'service', to: 'pages#service', as: 'service'

  resources :exercises do
    collection do
      get 'calculate_calories'
    end
  end

end

app/models/meal.rb
class Meal < ApplicationRecord
  enum meal_period: { breakfast: 0, lunch: 1, dinner: 2, nosh: 3 }
  enum meal_type: { self_catering: 0, eating_out: 1, to_go: 2, convenience_store: 3 }

  belongs_to :user
  has_many :meal_details, dependent: :destroy

  mount_uploader :meal_image, MealImageUploader

  validate :user_name_present

  private

  def user_name_present
    if user && user.name.blank?
      errors.add(:user, "name can't be blank")
    end
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!

  def index
    @meals = current_user.meals.includes(:meal_details, :user).order(meal_date: :desc).page(params[:page]).per(15)
  end

  def show
    @meal = Meal.find(params[:id])
    @user = @meal.user
  end

  def new
    @meal_form = MealForm.new
  end

  def edit
    load_meal
    @meal_form = MealForm.new(meal: @meal)
    redirect_to root_url, status: :see_other if @meal_form.nil?
  end

  def create
    @meal = Meal.new
    # フォームオブジェクトのインスタンスを作成
    @meal_form = MealForm.new(meal_params.merge(user_id: current_user.id))
  
    if @meal_form.save
      meal = @meal_form.meal
      redirect_to dashboard_path, success: t('defaults.message.created', item: Meal.model_name.human)
    else
      flash.now['error'] = t('defaults.message.not_created', item: Meal.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    load_meal
    @meal_form = MealForm.new(meal_params, meal: @meal)
    if @meal_form.save
      if params.dig(:meal, :meal_images).present?
        @meal.remove_meal_images! if @meal.meal_images.present?
        @meal.meal_images = params[:meal][:meal_images]
        @meal.save!
      end
      redirect_to dashboard_path, success: t('defaults.message.updated', item: Meal.model_name.human)
    else
      flash.now['error'] = t('defaults.message.not_updated', item: Meal.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meal = current_user.meals.find(params[:id])
    redirect_to root_url, status: :see_other if @meal.nil?
    @meal.destroy!
    redirect_to dashboard_path, success: t('defaults.message.deleted', item: Meal.model_name.human)
  end

  def calorie_search
    translated_text = DeeplApiService.new(params[:calorie_search]).call
    @response = NutritionApiService.new(translated_text).call
    @meal_form = MealForm.new
    render :new
  end

  def meals_feed
    @feed_items = Meal.includes(:user).where(user_id: [*current_user.following_ids]).order(meal_date: :desc).page(params[:page])
  end

  private

  def meal_params
    params.require(:meal).permit(:meal_date, :meal_period, :meal_type, :meal_memo,
                  :meal_title_first, :meal_weight_first, :meal_calorie_first,
                  :meal_title_second, :meal_weight_second, :meal_calorie_second,
                  :meal_title_third, :meal_weight_third, :meal_calorie_third, :meal_image)
end

 


  def load_meal
    @meal = current_user.meals.find(params[:id])
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_calorie_search.html.erb
<div class="calorie-search">
  <h2 class="text-xl font-bold my-4">カロリー検索（参考に使って下さい。100gあたりのカロリーを提示します。）</h2>
  <div class="mt-3">
    <%= form_with url: calorie_search_meals_path, method: :get, local: true do |f| %>
      <div class="form-control">
        <%= f.label :calorie_search, (t 'defaults.calorie_search') %>
        <%= f.text_field :calorie_search, class: "input input-bordered" %>
      </div>
      <div class="mt-4">
          <%= f.submit '検索する', class: "py-2 px-4 bg-blue-600 text-white rounded hover:bg-blue-700" %>
        </div>
    <% end %>
  </div>
  <% if response.present? %>
  <div class="flex flex-col border-4 border-primary-focus items-center m-4">
    <h2 class="text-xl font-bold my-4">検索結果</h2>
    <% response.each do |val| %>
      <div class="text-xl font-bold p-2">
        <%= val %>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/meals/_meal.html.erb
<div class="bg-white shadow-lg mx-4 my-2 md:w-96 rounded-lg overflow-hidden">
  <div class="relative h-40">
    <% if meal.meal_image.present? %>
  <%= image_tag meal.meal_image.thumb.url, class: "absolute h-full w-full object-cover" %>
<% else %>
  <%= image_tag('meal_sample.png', class: "absolute h-full w-full object-cover") %>
<% end %>
  </div>
  <div class="p-4 flex flex-row justify-between">
    <div>
      <%= link_to meal_path(meal.id) do %>
        <h2 class="text-lg font-bold truncate"><%= meal.meal_details.pluck(:meal_title).join(',') %></h2>
        <p><%= meal.meal_details.pluck(:meal_calorie).sum %> kcal / <%= meal.meal_period_i18n %></p>
        <p><%= meal.meal_date.strftime("%Y年%m月%d日") %></p>
      <% end %>
    </div>
    <div>
      <%= link_to profile_show_path(current_user.id) do %>
        <div class="flex items-center">
          <div class="w-12 h-12 relative mr-2">
            <% if meal.user.avatar.present? %>
              <%= image_tag meal.user.avatar.url(:thumb), class: "rounded-full object-cover w-full h-full border-2 border-primary-500" %>
            <% else %>
              <%= image_tag('default-avatar.png', class: "rounded-full object-cover w-full h-full border-2 border-primary-500") %>
            <% end %>
          </div>
          <p class="font-bold"><%= meal.user.name %></p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="p-4 border-t border-gray-200 flex justify-between">
    <%= button_to '削除', meal_path(meal), method: :delete, data: { confirm: "本当に削除しますか?" }, class: "text-red-500 hover:text-red-700" %>
  </div>
</div>

app/views/meals/edit.html.erb
<h1>Edit Meal</h1>

<%= render 'meal', meal: @meal %>

<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<% set_meta_tags title: (t '.title') %>
<div class="w-full">
  <div class="mx-auto">
    <div class="flex items-center">
      <h1 class="text-xl font-bold m-4"><%= t '.title' %></h1>
    </div>
    <div class="flex flex-wrap w-full">
      <% if @meals.present? %>
        <%= render @meals %>
      <% else %>
        <p><%= t('.no_result') %></p>
      <% end %>
    </div>
    <div class="flex justify-start md:justify-center btn-group w-screen m-8"><%= paginate @meals %></div>
  </div>
</div>

app/views/meals/new.html.erb
<% set_meta_tags title: (t '.title') %>
<div class="p-4 flex flex-col w-full">
  <h1 class="text-xl font-bold mb-6"><%= t '.title' %></h1>
  <%= turbo_frame_tag 'calorie_search' do %>
    <div>
      <%= render 'calorie_search', response: @response %>
    </div>
  <% end %>
  <div class="mt-6">
<%= form_with url: meals_path, method: :post, local: true, html: { enctype: 'multipart/form-data' }, scope: :meal do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <div>
        <div class="mb-4">
          <%= f.label :meal_date, class: "block text-xl font-bold mb-2" %>
          <%= f.date_field :meal_date, value: Time.now.strftime("%Y-%m-%d"), class: "p-2 border rounded w-full" %>
        </div>
        <div class="mb-4">
          <%= f.label :meal_period, class: "block text-xl font-bold mb-2" %>
          <%= f.select :meal_period, Meal.meal_periods.keys.map { |k| [I18n.t("enums.meal.meal_period.#{k}"), k] }, {}, class: "p-2 border rounded w-full" %>
        </div>
        <div class="mb-4">
          <%= f.label :meal_type, class: "block text-xl font-bold mb-2" %>
          <%= f.select :meal_type, Meal.meal_types.keys.map { |k| [I18n.t("enums.meal.meal_type.#{k}"), k] }, {}, class: "p-2 border rounded w-full" %>
        </div>
        <p class="mb-2">食事メニュー, グラム数, 総カロリーを最低1つ（1の欄）入力してください</p>
        <div data-controller="meal-detail-form">
          <div class="p-4 bg-gray-200 rounded">
            <div class="mb-4">
              <%= f.label :meal_title_first, class: "block text-xl font-bold mb-2" %>
              <%= f.text_field :meal_title_first, class: "p-2 border rounded w-full" %>
            </div>
            <div class="mb-4">
              <%= f.label :meal_weight_first, class: "block text-xl font-bold mb-2" %>
              <%= f.number_field :meal_weight_first, class: "p-2 border rounded w-full" %>
            </div>
            <div class="mb-4">
              <%= f.label :meal_calorie_first, class: "block text-xl font-bold mb-2" %>
              <%= f.number_field :meal_calorie_first, class: "p-2 border rounded w-full" %>
            </div>
          </div>
            <div class="p-4 bg-gray-200 rounded hidden" data-meal-detail-form-target="mealDetailForm">
            <div class="mb-4">
              <%= f.label :meal_title_second, class: "block text-xl font-bold mb-2" %>
              <%= f.text_field :meal_title_second, class: "p-2 border rounded w-full" %>
            </div>
            <div class="mb-4">
              <%= f.label :meal_weight_second, class: "block text-xl font-bold mb-2" %>
              <%= f.number_field :meal_weight_second, class: "p-2 border rounded w-full" %>
            </div>
            <div class="mb-4">
              <%= f.label :meal_calorie_second, class: "block text-xl font-bold mb-2" %>
              <%= f.number_field :meal_calorie_second, class: "p-2 border rounded w-full" %>
            </div>
          </div>
            <div class="p-4 bg-gray-200 rounded hidden" data-meal-detail-form-target="mealDetailForm">
            <div class="mb-4">
              <%= f.label :meal_title_third, class: "block text-xl font-bold mb-2" %>
              <%= f.text_field :meal_title_third, class: "p-2 border rounded w-full" %>
            </div>
            <div class="mb-4">
              <%= f.label :meal_weight_third, class: "block text-xl font-bold mb-2" %>
              <%= f.number_field :meal_weight_third, class: "p-2 border rounded w-full" %>
            </div>
            <div class="mb-4">
              <%= f.label :meal_calorie_third, class: "block text-xl font-bold mb-2" %>
              <%= f.number_field :meal_calorie_third, class: "p-2 border rounded w-full" %>
            </div>
          </div>
          <div class="flex">
            <%= button_tag type: "button", data: { action: "click->meal-detail-form#add" }, class: "add btn btn-ghost my-2" do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="w-8 text-primary" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 512c141.4 0 256-114.6 256-256S397.4 0 256 0S0 114.6 0 256S114.6 512 256 512zM232 344V280H168c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V168c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H280v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/></svg>
              <% end %>
              <%= button_tag type: "button", data: { action: "click->meal-detail-form#delete" }, class: "delete btn btn-ghost my-2" do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="w-8 text-primary" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M312 232C325.3 232 336 242.7 336 256C336 269.3 325.3 280 312 280H136C122.7 280 112 269.3 112 256C112 242.7 122.7 232 136 232H312zM0 96C0 60.65 28.65 32 64 32H384C419.3 32 448 60.65 448 96V416C448 451.3 419.3 480 384 480H64C28.65 480 0 451.3 0 416V96zM48 96V416C48 424.8 55.16 432 64 432H384C392.8 432 400 424.8 400 416V96C400 87.16 392.8 80 384 80H64C55.16 80 48 87.16 48 96z"/></svg>
              <% end %>
              <p class="m-2 self-center">メニュー3まで追加可能</p>
            </div>
          </div>
        <div class="mt-4">
          <%= f.label :meal_memo, class: "block text-xl font-bold mb-2" %>
          <%= f.text_area :meal_memo, class: "p-2 border rounded w-full" %>
        </div>
        <div class="mt-4">
          <%= f.label :meal_image, class: "block text-xl font-bold mb-2" %>
          <%= f.file_field :meal_image, class: "p-2 border rounded w-full"%>
        </div>
        <div class="mt-4">
          <%= f.submit '投稿する', class: "py-2 px-4 bg-blue-600 text-white rounded hover:bg-blue-700" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/meals/show.html.erb
<% set_meta_tags title: (t '.title') %>
<div class="m-8 flex flex-col w-full">
  <h1 class="text-xl font-bold"><%= t '.title' %></h1>
    <div class="grid card rounded-box place-items-center">
      <div class="flex max-w-full">
        <div class="avatar max-w-max my-8 mx-4">
          <div class="w-24 h-24 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
            <% if @user.avatar.present? %>
            <%= image_tag @meal.user.avatar.url(:thumb), class: "rounded-full object-cover w-full h-full border-2 border-primary-500" %>
            <% else %>
            <%= image_tag('default-avatar.png', size: "400x400") %>
            <% end %>
          </div>
        </div>
        <div class="flex flex-col">
          <div class="m-4">
            <h2 class="font-bold text-lg">ユーザー名</h2>
            <p><%= @user.name %><p>
        </div>
      </div>
    </div> 
    <div class="divider"></div> 
    <div class="grid card rounded-box">
      <div class="flex justify-around">
        <div class="w-2/5 flex flex-col align-center">
          <h2 class="text-xl font-bold my-4 text-center"><%= @meal.meal_date.strftime("%Y年%m月%d日") %></h2>
          <% if @meal.meal_image.present? %>
            <%= image_tag @meal.meal_image.url(:thumb), class: "flex items-center m-2" if @meal.meal_image.url.present? %>
              <% else %>
            <%= image_tag('meal_sample.png', size: "400x400") %>
          <% end %>
        </div>
        <div class="w-3/5 flex flex-col">
          <div class="mx-8 mt-4">
            <h2 class="text-xl font-bold">メニュー名</h2>
            <p class="text-base"><%= @meal.meal_details.pluck(:meal_title).join(' , ') %></p>
          </div>
          <div class="mx-8 mt-4">
            <h2 class="text-xl font-bold">食事タイミング</h2>
            <p class="text-base"><%= @meal.meal_period_i18n %></p>
          </div>
          <div class="mx-8 mt-4">
            <h2 class="text-xl font-bold">食事タイプ</h2>
            <p class="text-base"><%= @meal.meal_type_i18n %></p>
          </div>
          <div class="mx-8 mt-4">
            <h2 class="text-xl font-bold">カロリー</h2>
            <p class="text-base"><%= @meal.meal_details.pluck(:meal_calorie).sum %> kcal</p>
          </div>
          <div class="mx-8 mt-4">
            <h2 class="text-xl font-bold">メモ</h2>
            <p class="text-base md:w-96 break-words"><%= @meal.meal_memo %></p>
          </div>
          <div class="flex items-center mx-8 mt-4">
          </div>
          <div class="mx-8 mt-4">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>