config/routes.rb
Rails.application.routes.draw do
  # Deviseのルート設定
  devise_for :users, controllers: {
    # コントローラーやオプションがある場合、ここに追記
    registrations: 'users/registrations' 
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'application#guest_sign_in'
  end

  # Root URL設定
  root to: 'pages#home'

  # それぞれのリソースに関する標準のCRUDルート
  resources :meals do
    collection do
      get 'calorie_search'
    end
  end
  resources :exercises
  resources :badges, only: [:index, :show]
  resources :goals
  resources :posts
  resources :user_badges, only: [:create, :destroy]

  # ダッシュボード
  resource :dashboard, only: [:show]
  resource :profile, only: [:show, :edit, :update]
  get 'profile/:id', to: 'profiles#show', as: 'profile_show'

  get 'privacy', to: 'pages#privacy', as: 'privacy'
  get 'service', to: 'pages#service', as: 'service'

  resources :exercises do
    collection do
      get 'calculate_calories'
    end
  end

end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  def index
    @goals = Goal.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @goal = Goal.new
  end

  def edit
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user

    if @goal.save
      redirect_to @goal, notice: 'Goal was successfully created.'
    else
      render :new
    end
  end

  def update
    if @goal.update(goal_params)
      redirect_to @goal, notice: 'Goal was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @goal.destroy
    redirect_to goals_url, notice: 'Goal was successfully destroyed.'
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :description, :start_date, :end_date, :target_weight)
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: @goal, local: true) do |form| %>
  <% if @goal.errors.any? %>
    <div>
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>
      <ul>
        <% @goal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :target_weight %>
    <%= form.number_field :target_weight %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<% if @goal.new_record? %>
  <h1>New Goal</h1>
<% else %>
  <h1>Edit Goal</h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>Your Goals</h1>
<%= link_to 'New Goal', new_goal_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Target Weight</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.title %></td>
        <td><%= goal.description %></td>
        <td><%= goal.start_date %></td>
        <td><%= goal.end_date %></td>
        <td><%= goal.target_weight %></td>
        <td>
          <%= link_to 'Show', goal_path(goal) %>
          <%= link_to 'Edit', edit_goal_path(goal) %>
          <%= link_to 'Delete', goal_path(goal), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/goals/new.html.erb
<% if @goal.new_record? %>
  <h1>New Goal</h1>
<% else %>
  <h1>Edit Goal</h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @goal.start_date %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @goal.end_date %>
</p>

<p>
  <strong>Target Weight:</strong>
  <%= @goal.target_weight %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Delete', goal_path(@goal), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back',